version: "3.8"

services:
  mqtt-thermometer:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: mqtt-thermometer
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config/mqtt-thermometer-home.toml:/app/config/mqtt-thermometer.toml:ro
      - ./data:/app/data
    environment:
      - MQTT_THERMOMETER_CONFIG_PATH=/app/config/mqtt-thermometer.toml
      - MQTT_THERMOMETER_DB_PATH=/app/data/mqtt-thermometer.db
    networks:
      - mqtt-network

  # Optional: Local MQTT broker for testing
  mosquitto:
    image: eclipse-mosquitto:2-openssl
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge

volumes:
  data:
    driver: local
