name: Deploy service

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin/uv" >> $GITHUB_PATH

      - name: Build
        run: |
          uv sync

      - name: Blue-green deployment
        run: |
          sudo cp /srv/mqtt-thermometer/*.db .
          sudo cp /srv/mqtt-thermometer/mqtt-thermometer.toml .

          sudo systemctl stop mqtt-thermometer.service || true
          sudo rm /etc/systemd/system/mqtt-thermometer.service || true
          sudo rm -rf /srv/mqtt-thermometer/*
          sudo mv .* /srv/mqtt-thermometer/ 2>/dev/null || true
          sudo mv * /srv/mqtt-thermometer/

          sudo ln -s /srv/mqtt-thermometer/mqtt-thermometer.service /etc/systemd/system/mqtt-thermometer.service
          sudo systemctl daemon-reload
          sudo systemctl enable mqtt-thermometer.service
          sudo systemctl start mqtt-thermometer.service

      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf $GITHUB_WORKSPACE/*
          rm -rf $GITHUB_WORKSPACE/.??*
