name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      # Application code that affects the Docker image
      - "mqtt_thermometer/**"
      - "scripts/**"
      # Docker and deployment configuration
      - "Dockerfile"
      - "docker-compose*.yml"
      - ".github/workflows/docker-cicd.yml"
      # Dependencies and project configuration
      - "pyproject.toml"
      - "uv.lock"
      # Deployment configurations
      - "config/mqtt-thermometer-home.toml"
      - "config/mqtt-thermometer-cottage.toml"
      - "scripts/setup-raspi.sh"
  # Allow manual workflow dispatch for testing
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mqtt-thermometer

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optimized caching for GitHub free plan
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}

  deploy-home:
    name: Deploy to Raspberry Pi Home
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, Linux, ARM64, raspi-home]
    steps:
      - name: Checkout repository (for deployment files)
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Docker container
        run: |
          # Ensure deployment directory exists with proper permissions
          sudo mkdir -p /srv/mqtt-thermometer/data
          sudo chown -R 1000:1000 /srv/mqtt-thermometer/data

          # Copy production Docker Compose file
          sudo cp docker-compose.production.yml /srv/mqtt-thermometer/docker-compose.yml

          # Copy home-specific configuration
          sudo cp config/mqtt-thermometer-home.toml /srv/mqtt-thermometer/mqtt-thermometer.toml          # Navigate to deployment directory
          cd /srv/mqtt-thermometer

          # Stop existing services
          docker compose down || true

          # Clean up old/unused images on Pi
          docker image prune -f

          # Pull latest image
          docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

          # Start services with new image
          docker compose up -d

      - name: Verify deployment
        run: |
          cd /srv/mqtt-thermometer

          # Wait for container to reach healthy status (up to 2 minutes)
          echo "Waiting for container to become healthy..."
          for i in {1..24}; do
            health_status=$(docker compose ps --format "table {{.Name}}\t{{.Status}}" | grep mqtt-thermometer | awk '{print $NF}' | tr -d '()')
            if [[ "$health_status" == "healthy" ]]; then
              echo "Container is healthy!"
              break
            elif [ $i -eq 24 ]; then
              echo "Timeout: Container did not become healthy within 2 minutes"
              echo "Current status: $health_status"
              docker compose ps
              docker compose logs mqtt-thermometer
              exit 1
            else
              echo "Attempt $i/24: Container status is '$health_status', waiting..."
              sleep 5
            fi
          done

          # Additional validation: verify the service responds correctly
          echo "Testing service endpoint..."
          if curl -f --max-time 10 http://localhost:8000/temperatures > /dev/null 2>&1; then
            echo "Service endpoint is responding correctly"
          else
            echo "Service endpoint failed to respond"
            docker compose ps
            docker compose logs mqtt-thermometer
            exit 1
          fi

          # Show final status
          docker compose ps

  deploy-cottage:
    name: Deploy to Raspberry Pi Cottage
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, Linux, ARM64, raspi-cottage]
    steps:
      - name: Checkout repository (for deployment files)
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Docker container
        run: |
          # Ensure deployment directory exists with proper permissions
          sudo mkdir -p /srv/mqtt-thermometer/data
          sudo chown -R 1000:1000 /srv/mqtt-thermometer/data

          # Copy production Docker Compose file
          sudo cp docker-compose.production.yml /srv/mqtt-thermometer/docker-compose.yml

          # Copy cottage-specific configuration
          sudo cp config/mqtt-thermometer-cottage.toml /srv/mqtt-thermometer/mqtt-thermometer.toml          # Navigate to deployment directory
          cd /srv/mqtt-thermometer

          # Stop existing services
          docker compose down || true

          # Clean up old/unused images on Pi
          docker image prune -f

          # Pull latest image
          docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

          # Start services with new image
          docker compose up -d

      - name: Verify deployment
        run: |
          cd /srv/mqtt-thermometer

          # Wait for container to reach healthy status (up to 2 minutes)
          echo "Waiting for container to become healthy..."
          for i in {1..24}; do
            health_status=$(docker compose ps --format "table {{.Name}}\t{{.Status}}" | grep mqtt-thermometer | awk '{print $NF}' | tr -d '()')
            if [[ "$health_status" == "healthy" ]]; then
              echo "Container is healthy!"
              break
            elif [ $i -eq 24 ]; then
              echo "Timeout: Container did not become healthy within 2 minutes"
              echo "Current status: $health_status"
              docker compose ps
              docker compose logs mqtt-thermometer
              exit 1
            else
              echo "Attempt $i/24: Container status is '$health_status', waiting..."
              sleep 5
            fi
          done

          # Additional validation: verify the service responds correctly
          echo "Testing service endpoint..."
          if curl -f --max-time 10 http://localhost:8000/temperatures > /dev/null 2>&1; then
            echo "Service endpoint is responding correctly"
          else
            echo "Service endpoint failed to respond"
            docker compose ps
            docker compose logs mqtt-thermometer
            exit 1
          fi

          # Show final status
          docker compose ps
