name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mqtt-thermometer

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-metadata: ${{ steps.meta.outputs.json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export image as tar for self-hosted runners
        if: github.ref == 'refs/heads/master'
        run: |
          # Pull the image we just built
          docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

          # Save as tar file
          docker save ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest -o mqtt-thermometer-latest.tar

          # Compress for faster transfer
          gzip mqtt-thermometer-latest.tar

      - name: Upload Docker image artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: mqtt-thermometer-latest.tar.gz
          retention-days: 7

  deploy-home:
    name: Deploy to Raspberry Pi Home
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: raspi-home
    environment:
      name: home
      url: http://192.168.1.x:8000
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load and run Docker container
        run: |
          # Navigate to deployment directory
          cd /srv/mqtt-thermometer

          # Stop existing services
          docker-compose down || true

          # Load new image
          gunzip ~/mqtt-thermometer-latest.tar.gz
          docker load -i ~/mqtt-thermometer-latest.tar

          # Tag the loaded image to match docker-compose expectation
          docker tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest ghcr.io/vuorinet/mqtt-thermometer:latest

          # Start services with new image
          docker-compose up -d

          # Clean up
          rm ~/mqtt-thermometer-latest.tar

      - name: Verify deployment
        run: |
          # Wait for container to start
          sleep 10

          # Check if container is running
          cd /srv/mqtt-thermometer
          docker-compose ps | grep mqtt-thermometer

          # Health check
          curl -f http://localhost:8000/temperatures || exit 1

  deploy-cottage:
    name: Deploy to Raspberry Pi Cottage
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: raspi-cottage
    environment:
      name: cottage
      url: http://cottage.local:8000
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load and run Docker container
        run: |
          # Navigate to deployment directory
          cd /srv/mqtt-thermometer

          # Stop existing services
          docker-compose down || true

          # Load new image
          gunzip ~/mqtt-thermometer-latest.tar.gz
          docker load -i ~/mqtt-thermometer-latest.tar

          # Tag the loaded image to match docker-compose expectation
          docker tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest ghcr.io/vuorinet/mqtt-thermometer:latest

          # Start services with new image
          docker-compose up -d

          # Clean up
          rm ~/mqtt-thermometer-latest.tar

      - name: Verify deployment
        run: |
          # Wait for container to start
          sleep 10

          # Check if container is running
          cd /srv/mqtt-thermometer
          docker-compose ps | grep mqtt-thermometer

          # Health check
          curl -f http://localhost:8000/temperatures || exit 1
